# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference
name: Azat Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Qwen 2.5 Coder 14B
    provider: ollama
    model: qwen2.5-coder:14b
    roles:
      - apply
      - autocomplete
      - chat
      - edit
  